# Generated by Django 5.0.6 on 2024-05-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('first_published_year', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('first_sentence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=200)),
                ('currently_reading', models.CharField(max_length=100)),
                ('favourite_book', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BooksReadByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('note', models.CharField(max_length=2500, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.user')),
            ],
        ),
    ]
