# Generated by Django 5.0.6 on 2024-05-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_booksreadbyuser_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='first_published_year',
            new_name='first_publish_year',
        ),
    ]
