# Generated by Django 5.0.6 on 2024-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_rename_first_published_year_book_first_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_sentence',
            field=models.CharField(max_length=10000),
        ),
    ]
