# Generated by Django 5.0.6 on 2024-06-01 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_first_sentence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksabandonedbyuser',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='booksreadbyuser',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='bookstobereadbyuser',
            unique_together={('user', 'book')},
        ),
    ]
