# Generated by Django 5.0.6 on 2024-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_booksabandonedbyuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
